title: ADR or bust!
author: Myself
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sadly I'm learning how to work with Github Pages late in the game. This is so embarassing.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
